version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: kenya_health_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 7510
      POSTGRES_DB: kenya_health_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:2.10.1
    container_name: kenya_health_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:7510@postgres/kenya_health_db
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      AIRFLOW_UID: 50000
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./dbt:/opt/airflow/dbt
    command: >
      bash -c "
        airflow db init &&
        airflow users create \
          --username faust \
          --password 44444444 \
          --firstname De \
          --lastname Clerke \
          --role Admin \
          --email idankan751@gmail.com || true &&
        pip install dbt-postgres pandas sqlalchemy psycopg2-binary &&
        airflow webserver & airflow scheduler
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: kenya_health_metabase
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: kenya_health_db
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: '7510'
      MB_DB_HOST: postgres
    volumes:
      - metabase_data:/metabase-data

volumes:
  postgres_data:
  metabase_data: